### ISSUE TITLE
RAG support

### ISSUE THREAD

**Issue by sandangel** [nomnivore/ollama.nvim#9]
It would be great if we can support RAG on top of Ollama model. We can configure a folder where we can etrieve documents and then provide it to ollama model. WDYT?

**Comment by nomnivore** [comment]
This plugin is meant to act as a communication layer between nvim and ollama, not an augmentation of ollama's capabilities. As far as I know, this would be out of spec.

It would probably be better to explore other methods of achieving this, such as a custom API, since this plugin just uses http anyway.

**Comment by sandangel** [comment]
Having a custom API sounds great, so that user can use their own RAG and leverage this plugin communication layer and UI.

**Comment by sandangel** [comment]
@nomnivore is it possible that we add support for that? I can also help with the design.

**Comment by nomnivore** [comment]
An intermediary API is out of spec for a neovim plugin - that would be up to the user to set up.
